spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    defer-datasource-initialization: true

logging:
  level:
    bitcoin: debug

bitquery:
  api-key: BQYk5N3MypMuNtqXmZ81uiNsE7BR9Uup
  api-url: https://graphql.bitquery.io
server:
  error:
    include-binding-errors: always
    include-message: always
    include-exception: false
    include-stacktrace: never